language: cpp
compiler: gcc
os: linux
dist: rusty
sudo: require

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - valgrind
